inherit_gem:
    bixby: bixby_default.yml

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
