inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - "bin/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/system/**/*"
    - "spec/requests/**/*"
    - "spec/support/shared_examples/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/system/**/*"
    - "spec/requests/**/*"
    - "spec/support/**/*"
    - "config/environments/**/*"
